theme: jekyll-theme-midnight
Title: Complex Objects Projects
Description: A collection of my projects in unsupervised learning, particle simulation, complex networks, convolutional neural nets, and reinforcement learning
